/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-12-16 07:30:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1734163616750L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1734329742771L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>About</title>\r\n");
      out.write("<link rel=\"icon\" href=\"assets/logo.png\" type=\"image/png\" >\r\n");
      out.write("<style>\r\n");
      out.write("    * {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        font-family: 'Arial', sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        background-color: #f5f5f5;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        overflow-x: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    header {\r\n");
      out.write("	    background:  url(\"assets/about.jpg\") no-repeat center center;\r\n");
      out.write("	    background-size: cover;\r\n");
      out.write("	    object-fit: cover;\r\n");
      out.write("		color: #ffffff;\r\n");
      out.write("	    padding: 5px 5px;\r\n");
      out.write("	    text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("    header h1 {\r\n");
      out.write("        font-size: 3rem;\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    header p {\r\n");
      out.write("        font-size: 1.2rem;\r\n");
      out.write("        margin-top:150px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .mission-vision-section {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        gap: 30px;\r\n");
      out.write("        margin: 15px;\r\n");
      out.write("        padding: 50px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .mission-vision-card {\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        width: 500px;\r\n");
      out.write("        transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .mission-vision-card img {\r\n");
      out.write("        width: 120px;\r\n");
      out.write("        height: 120px;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .mission-vision-card h2 {\r\n");
      out.write("        font-size: 2rem;\r\n");
      out.write("        color: #2575fc;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .mission-vision-card p {\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        line-height: 1.6;\r\n");
      out.write("        color: #555;\r\n");
      out.write("        margin : 10px;\r\n");
      out.write("        text-align: justify;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .about-section {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        padding: 20px 10px;\r\n");
      out.write("        gap: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .about-card {\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .about-card:hover {\r\n");
      out.write("        transform: translateY(-10px);\r\n");
      out.write("        box-shadow: 0 8px 12px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .about-card img {\r\n");
      out.write("        width: 100px;\r\n");
      out.write("        height: 100px;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .about-card h3 {\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("        font-size: 1.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .about-card p {\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("        color: #666;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        header h1 {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .mission-vision-card {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 400px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-card {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 300px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- NavBar -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Gen Sea Tech</title>\r\n");
      out.write("<link rel=\"icon\" href=\"assets/logo.png\" type=\"image/png\" >\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	line-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write(".navbar {\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	padding: 5px 5px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar a {\r\n");
      out.write("	color: #40c4ff;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	margin: 0 20px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar a:hover {\r\n");
      out.write("	color: #757575;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".links {\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("	.links {\r\n");
      out.write("		display: none;\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("		background-color: #333;\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		top: 50px;\r\n");
      out.write("		right: 10px;\r\n");
      out.write("		width: 200px;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("		box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.links a {\r\n");
      out.write("		margin: 10px 0;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.hamburger {\r\n");
      out.write("		display: flex;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.links.active {\r\n");
      out.write("		display: flex;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"navbar\">\r\n");
      out.write("		<div class=\"logo\">\r\n");
      out.write("        <a href=\"home.jsp\"><img src=\"assets/namelogo.png\" alt=\"Gen Sea Tech Logo\" style=\"height: 60px; margin-right: 10px;\"></a>\r\n");
      out.write("    	</div>\r\n");
      out.write("		<div class=\"links\">\r\n");
      out.write("			<a href=\"home.jsp\">Home</a>\r\n");
      out.write("			<a href=\"services.jsp\">Services</a>\r\n");
      out.write("			<a href=\"products.jsp\">Products</a>\r\n");
      out.write("			<a href=\"connectus.jsp\">Connect Us</a>\r\n");
      out.write("			<a href=\"about.jsp\">About</a>\r\n");
      out.write("			<a href=\"#support.jsp\">Support</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    <header>\r\n");
      out.write("        <p>Gen Sea Tech</p>\r\n");
      out.write("        <h5>Where Ideas Meet Technology.</h5>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"mission-vision-section\">\r\n");
      out.write("        <div class=\"mission-vision-card\">\r\n");
      out.write("            <img src=\"assets/mission.jpg\" alt=\"Mission Icon\">\r\n");
      out.write("            <h2>Our Mission</h2>\r\n");
      out.write("            <p>At Gen Sea Tech, our mission is to deliver innovative and reliable technology solutions that simplify everyday life, empowering individuals and businesses to thrive in a rapidly evolving world.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mission-vision-card\">\r\n");
      out.write("            <img src=\"assets/vision.jpg\" alt=\"Vision Icon\">\r\n");
      out.write("            <h2>Our Vision</h2>\r\n");
      out.write("            <p>To become a global leader in transformative technology solutions, making life easier and more efficient for everyone, every day.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"about-section\" id=\"team\">\r\n");
      out.write("        <div class=\"about-card\">\r\n");
      out.write("            <img src=\"https://via.placeholder.com/100\" alt=\"Team Member\">\r\n");
      out.write("            <h3>Name Here</h3>\r\n");
      out.write("            <p>CEO & Founder</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"about-card\">\r\n");
      out.write("            <img src=\"https://via.placeholder.com/100\" alt=\"Team Member\">\r\n");
      out.write("            <h3>Name Here</h3>\r\n");
      out.write("            <p>Lead Developer</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"about-card\">\r\n");
      out.write("            <img src=\"https://via.placeholder.com/100\" alt=\"Team Member\">\r\n");
      out.write("            <h3>Name Here</h3>\r\n");
      out.write("            <p>UI/UX Designer</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	footer {\r\n");
      out.write("        background-color: #333;\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("        margin-top: 0px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    footer p {\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<footer>\r\n");
      out.write("        <p>&copy; Gen Sea Tech. All rights reserved.</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
