/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-12-04 12:07:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1733314039155L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Contacts</title>\r\n");
      out.write("<link rel=\"icon\" href=\"assets/logo.png\" type=\"image/png\" >\r\n");
      out.write("<style>\r\n");
      out.write("    * {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        font-family: 'Arial', sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        background-color: #f5f5f5;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        overflow-x: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    header {\r\n");
      out.write("        background: linear-gradient(135deg, #6a11cb, #2575fc);\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 30px 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    header h1 {\r\n");
      out.write("        font-size: 3rem;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    header p {\r\n");
      out.write("        font-size: 1.2rem;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .connect-section {\r\n");
      out.write("        background: #f9f9f9;\r\n");
      out.write("        padding: 50px 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .connect-section h2 {\r\n");
      out.write("        font-size: 2rem;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .connect-links {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        margin-up: 20px;\r\n");
      out.write("        gap: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .connect-card {\r\n");
      out.write("    background: white;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    width: 150px;\r\n");
      out.write("    transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("    text-decoration: none; /* Removes underline from links */\r\n");
      out.write("    color: #333; /* Default text color */\r\n");
      out.write("    display: block; /* Makes the link behave as a block element */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".connect-card:hover {\r\n");
      out.write("    transform: translateY(-10px);\r\n");
      out.write("    box-shadow: 0 8px 12px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".connect-card img {\r\n");
      out.write("    width: 50px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".connect-card span {\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #2575fc;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    footer {\r\n");
      out.write("        background-color: #333;\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        margin-top: 50px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    footer p {\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        header h1 {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-card, .connect-card {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 400px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Gen Sea Tech</title>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	line-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write(".navbar {\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	padding: 5px 5px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar a {\r\n");
      out.write("	color: #40c4ff;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	margin: 0 20px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar a:hover {\r\n");
      out.write("	color: #757575;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".links {\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("	.links {\r\n");
      out.write("		display: none;\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("		background-color: #333;\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		top: 50px;\r\n");
      out.write("		right: 10px;\r\n");
      out.write("		width: 200px;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("		box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.links a {\r\n");
      out.write("		margin: 10px 0;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.hamburger {\r\n");
      out.write("		display: flex;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.links.active {\r\n");
      out.write("		display: flex;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"navbar\">\r\n");
      out.write("		<div class=\"logo\">\r\n");
      out.write("        <a href=\"home.jsp\"><img src=\"assets/namelogo.png\" alt=\"Gen Sea Tech Logo\" style=\"height: 60px; margin-right: 10px;\"></a>\r\n");
      out.write("    	</div>\r\n");
      out.write("		<div class=\"links\">\r\n");
      out.write("			<a href=\"home.jsp\">Home</a>\r\n");
      out.write("			<a href=\"services.jsp\">Services</a>\r\n");
      out.write("			<a href=\"products.jsp\">Products</a>\r\n");
      out.write("			<a href=\"contact.jsp\">Contact</a>\r\n");
      out.write("			<a href=\"about.jsp\">About</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <h1>Contacts</h1>\r\n");
      out.write("        <p>We are passionate about creating innovative solutions for a better tomorrow.</p>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"connect-section\">\r\n");
      out.write("        <h2>Connect With Us</h2>\r\n");
      out.write("        <div class=\"connect-links\">\r\n");
      out.write("		    <a href=\"https://wa.me/9325156075\" target=\"_blank\" class=\"connect-card\">\r\n");
      out.write("		        <img src=\"https://img.icons8.com/?size=100&id=bbCdIvHZ3OjJ&format=png&color=000000\" alt=\"WhatsApp\">\r\n");
      out.write("		        <span>WhatsApp</span>\r\n");
      out.write("		    </a>\r\n");
      out.write("		    <a href=\"mailto:your-email@example.com\" class=\"connect-card\">\r\n");
      out.write("		        <img src=\"https://img.icons8.com/?size=100&id=19408&format=png&color=000000\" alt=\"Email\">\r\n");
      out.write("		        <span>Email/Gmail</span>\r\n");
      out.write("		    </a>\r\n");
      out.write("		    <a href=\"https://linkedin.com/in/your-profile\" target=\"_blank\" class=\"connect-card\">\r\n");
      out.write("		        <img src=\"https://img.icons8.com/?size=100&id=xuvGCOXi8Wyg&format=png&color=000000\" alt=\"LinkedIn\">\r\n");
      out.write("		        <span>LinkedIn</span>\r\n");
      out.write("		    </a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"connect-links\">\r\n");
      out.write("		    <a href=\"https://instagram.com/your-profile\" target=\"_blank\" class=\"connect-card\">\r\n");
      out.write("		        <img src=\"https://img.icons8.com/?size=100&id=YtpeVQhQ8USm&format=png&color=000000\" alt=\"Instagram\">\r\n");
      out.write("		        <span>Instagram</span>\r\n");
      out.write("		    </a>\r\n");
      out.write("		    <a href=\"https://instagram.com/your-profile\" target=\"_blank\" class=\"connect-card\">\r\n");
      out.write("		        <img src=\"https://img.icons8.com/?size=80&id=phOKFKYpe00C&format=png&color=000000\" alt=\"X\">\r\n");
      out.write("		        <span>X/Twitter</span>\r\n");
      out.write("		    </a>\r\n");
      out.write("		    <a href=\"https://discord.gg/your-invite\" target=\"_blank\" class=\"connect-card\">\r\n");
      out.write("		        <img src=\"https://img.icons8.com/?size=100&id=D2NqKl85S8Ye&format=png&color=000000\" alt=\"Discord\">\r\n");
      out.write("		        <span>Discord</span>\r\n");
      out.write("		    </a>\r\n");
      out.write("		</div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <p>&copy; 2024 Gen Sea Tech. All rights reserved.</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
