/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-12-17 08:53:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1734163616750L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1734329742771L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Gen Sea Tech</title>\r\n");
      out.write("<link rel=\"icon\" href=\"assets/logo.png\" type=\"image/png\" >\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	* {\r\n");
      out.write("		margin: 0;\r\n");
      out.write("		padding: 0;\r\n");
      out.write("		box-sizing: border-box;\r\n");
      out.write("		font-family: Arial, sans-serif;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	body {\r\n");
      out.write("		line-height: 1.6;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	header p {\r\n");
      out.write("        font-size: 1.2rem;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("	\r\n");
      out.write("	.hero {\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		background: url('assets/hero-bg.jpg') no-repeat center center/cover;\r\n");
      out.write("		color: #000000;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		padding: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.hero h1 {\r\n");
      out.write("		font-size: 3rem;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.hero p {\r\n");
      out.write("		margin-top: 10px;\r\n");
      out.write("		font-size: 1.2rem;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.section {\r\n");
      out.write("		padding: 50px 20px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.section h2 {\r\n");
      out.write("		font-size: 2rem;\r\n");
      out.write("		margin-bottom: 20px;\r\n");
      out.write("		color: #333;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.section p {\r\n");
      out.write("		margin-bottom: 20px;\r\n");
      out.write("		font-size: 1rem;\r\n");
      out.write("		color: #666;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.cards {\r\n");
      out.write("		display: grid;\r\n");
      out.write("		grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\r\n");
      out.write("		gap: 20px;\r\n");
      out.write("		margin-top: 20px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.card {\r\n");
      out.write("		background: #f4f4f4;\r\n");
      out.write("		padding: 20px;\r\n");
      out.write("		border-radius: 10px;\r\n");
      out.write("		box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.card h3 {\r\n");
      out.write("		margin-bottom: 10px;\r\n");
      out.write("		font-size: 1.2rem;\r\n");
      out.write("		color: #555;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.card p {\r\n");
      out.write("		font-size: 0.9rem;\r\n");
      out.write("		color: #777;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.contact {\r\n");
      out.write("		background: #00bcd4;\r\n");
      out.write("		color: #fff;\r\n");
      out.write("		padding: 50px 20px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.contact h2 {\r\n");
      out.write("		margin-bottom: 20px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.contact form {\r\n");
      out.write("		max-width: 600px;\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.contact input, .contact textarea {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("		margin-bottom: 10px;\r\n");
      out.write("		border: none;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.contact button {\r\n");
      out.write("		padding: 10px 20px;\r\n");
      out.write("		border: none;\r\n");
      out.write("		background: #008c9e;\r\n");
      out.write("		color: white;\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.contact button:hover {\r\n");
      out.write("		background: #006b76;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.address {\r\n");
      out.write("		background:  url(\"assets/contactus.jpg\") no-repeat center center;\r\n");
      out.write("	    background-size: cover;\r\n");
      out.write("	    object-fit: cover;\r\n");
      out.write("		padding: 30px;\r\n");
      out.write("		color: #ffffff;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.address h3 {\r\n");
      out.write("		margin-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.address p {\r\n");
      out.write("		margin-bottom: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	.scroll-container {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        overflow-x: auto;\r\n");
      out.write("        margin-left: 50px;\r\n");
      out.write("        margin-right: 50px;\r\n");
      out.write("        gap: 20px;\r\n");
      out.write("        padding: 20px 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .review-card {\r\n");
      out.write("        min-width: 300px;\r\n");
      out.write("        background: #f4f4f4;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .review-card h3 {\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("        font-size: 1.2rem;\r\n");
      out.write("        color: #555;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .review-card p {\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("        color: #777;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .scroll-container::-webkit-scrollbar {\r\n");
      out.write("        height: 8px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .scroll-container::-webkit-scrollbar-thumb {\r\n");
      out.write("        background-color: #00bcd4;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .scroll-container::-webkit-scrollbar-track {\r\n");
      out.write("        background: #f4f4f4;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- NavBar -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Gen Sea Tech</title>\r\n");
      out.write("<link rel=\"icon\" href=\"assets/logo.png\" type=\"image/png\" >\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	line-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write(".navbar {\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	padding: 5px 5px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar a {\r\n");
      out.write("	color: #40c4ff;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	margin: 0 20px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar a:hover {\r\n");
      out.write("	color: #757575;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".links {\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("	.links {\r\n");
      out.write("		display: none;\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("		background-color: #333;\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		top: 50px;\r\n");
      out.write("		right: 10px;\r\n");
      out.write("		width: 200px;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("		box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.links a {\r\n");
      out.write("		margin: 10px 0;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.hamburger {\r\n");
      out.write("		display: flex;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.links.active {\r\n");
      out.write("		display: flex;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"navbar\">\r\n");
      out.write("		<div class=\"logo\">\r\n");
      out.write("        <a href=\"home.jsp\"><img src=\"assets/namelogo.png\" alt=\"Gen Sea Tech Logo\" style=\"height: 60px; margin-right: 10px;\"></a>\r\n");
      out.write("    	</div>\r\n");
      out.write("		<div class=\"links\">\r\n");
      out.write("			<a href=\"home.jsp\">Home</a>\r\n");
      out.write("			<a href=\"services.jsp\">Services</a>\r\n");
      out.write("			<a href=\"products.jsp\">Products</a>\r\n");
      out.write("			<a href=\"connectus.jsp\">Connect Us</a>\r\n");
      out.write("			<a href=\"about.jsp\">About</a>\r\n");
      out.write("			<a href=\"#support.jsp\">Support</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Hero Section -->\r\n");
      out.write("	<div class=\"hero\">\r\n");
      out.write("		<div>\r\n");
      out.write("			<h1>Welcome to Gen Sea Tech</h1>\r\n");
      out.write("			<p>Innovating for a better tomorrow</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Who We Are Section -->\r\n");
      out.write("	<div class=\"section\" id=\"about\">\r\n");
      out.write("		<h2>Who We Are</h2>\r\n");
      out.write("		<p>Gen Sea Tech is a forward-thinking company dedicated to creating cutting-edge technology solutions that simplify and enhance day-to-day life.</p>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Mission & Vision Section -->\r\n");
      out.write("	<div class=\"section\" id=\"mission-vision\">\r\n");
      out.write("		<h2>Our Mission & Vision</h2>\r\n");
      out.write("		<p><strong>Mission:</strong> To deliver innovative, scalable, and sustainable tech solutions tailored to our clients' needs.</p>\r\n");
      out.write("		<p><strong>Vision:</strong> To be a global leader in technology, inspiring progress and driving change through our solutions.</p>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Products Section -->\r\n");
      out.write("	<div class=\"section\" id=\"products\">\r\n");
      out.write("		<h2>Our Products</h2>\r\n");
      out.write("		<p>Explore our range of innovative products designed to improve efficiency and productivity.</p>\r\n");
      out.write("		<div class=\"cards\">\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("				<h3>Product 1</h3>\r\n");
      out.write("				<p>Details about the product and its benefits.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("				<h3>Product 2</h3>\r\n");
      out.write("				<p>Details about the product and its benefits.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("				<h3>Product 3</h3>\r\n");
      out.write("				<p>Details about the product and its benefits.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Services Section -->\r\n");
      out.write("	<div class=\"section\" id=\"services\">\r\n");
      out.write("		<h2>Our Services</h2>\r\n");
      out.write("		<p>Providing top-notch services tailored to meet your business needs.</p>\r\n");
      out.write("		<div class=\"cards\">\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("				<h3>Custom Software Development</h3>\r\n");
      out.write("				<p>Tailored solutions designed to meet your unique business needs.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("				<h3>AI and Machine Learning</h3>\r\n");
      out.write("				<p>Empowering businesses with intelligent data-driven decisions.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("				<h3>Web and Mobile Apps</h3>\r\n");
      out.write("				<p>Creating seamless, user-friendly experiences for your customers.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Testimonials Section -->\r\n");
      out.write("	<div class=\"section\" id=\"testimonials\">\r\n");
      out.write("	    <h2>Customer Reviews</h2>\r\n");
      out.write("	    <p>See what our satisfied customers have to say about Gen Sea Tech.</p>\r\n");
      out.write("	    <div class=\"scroll-container\">\r\n");
      out.write("	        <div class=\"review-card\">\r\n");
      out.write("	            <h3>John Doe</h3>\r\n");
      out.write("	            <p>\"Gen Sea Tech transformed our business with their innovative solutions!\"</p>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"review-card\">\r\n");
      out.write("	            <h3>Jane Smith</h3>\r\n");
      out.write("	            <p>\"The team at Gen Sea Tech is highly skilled and professional. Highly recommend!\"</p>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"review-card\">\r\n");
      out.write("	            <h3>Mark Wilson</h3>\r\n");
      out.write("	            <p>\"Fantastic experience working with Gen Sea Tech. Their products are top-notch!\"</p>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"review-card\">\r\n");
      out.write("	            <h3>John Doe</h3>\r\n");
      out.write("	            <p>\"Gen Sea Tech transformed our business with their innovative solutions!\"</p>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"review-card\">\r\n");
      out.write("	            <h3>Jane Smith</h3>\r\n");
      out.write("	            <p>\"The team at Gen Sea Tech is highly skilled and professional. Highly recommend!\"</p>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"review-card\">\r\n");
      out.write("	            <h3>Mark Wilson</h3>\r\n");
      out.write("	            <p>\"Fantastic experience working with Gen Sea Tech. Their products are top-notch!\"</p>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"review-card\">\r\n");
      out.write("	            <h3>John Doe</h3>\r\n");
      out.write("	            <p>\"Gen Sea Tech transformed our business with their innovative solutions!\"</p>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"review-card\">\r\n");
      out.write("	            <h3>Jane Smith</h3>\r\n");
      out.write("	            <p>\"The team at Gen Sea Tech is highly skilled and professional. Highly recommend!\"</p>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"review-card\">\r\n");
      out.write("	            <h3>Mark Wilson</h3>\r\n");
      out.write("	            <p>\"Fantastic experience working with Gen Sea Tech. Their products are top-notch!\"</p>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Address Section -->\r\n");
      out.write("	<div class=\"address\" id=\"contact\">\r\n");
      out.write("		<h3>Contact Us</h3>\r\n");
      out.write("		<p><strong>Office:</strong> 3rd Floor, Gen Sea Tech Office, Dhayari, Pune, Maharashtra 411041.</p>\r\n");
      out.write("		<p><strong>Email:</strong> genseatech@gmail.com</p>\r\n");
      out.write("		<p><strong>Phone:</strong> +91-602-612-6624.</p>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	footer {\r\n");
      out.write("        background-color: #333;\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("        margin-top: 0px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    footer p {\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<footer>\r\n");
      out.write("        <p>&copy; Gen Sea Tech. All rights reserved.</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
